# Generated by Django 2.1.7 on 2019-03-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Boolean'), (2, 'Integer'), (3, 'Float'), (4, 'String')])),
                ('value', models.CharField(max_length=250)),
            ],
        ),
    ]
